Resolved issue of app hanging in lower end phones
PSMRI/HWC-Mobile-App pull request #15
Opened 2024-10-12 17:59 UTC by Thejas775

## 📋 Description

Resolved issue of app hanging and crashing in lower end phones

2024-10-12 17:59 UTC, Thejas775 commented
@NikhilFegade

2024-10-13 03:43 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/cho/ui/register_patient_activity/patient_details/PatientDetailsFragment.kt
> +//            lifecycleScope.launch(Dispatchers.IO) {
Please don't commit commented out code.

2024-10-13 03:44 UTC, drtechie commented
Code doesn't look DRY.

2024-10-13 07:15 UTC, Thejas775 commented on app/src/main/java/org/piramalswasthya/cho/ui/register_patient_activity/patient_details/PatientDetailsFragment.kt
> +//            lifecycleScope.launch(Dispatchers.IO) {
Okay

2024-10-14 05:32 UTC, NikhilFegade requested changes

2024-10-14 05:32 UTC, NikhilFegade commented on app/src/main/java/org/piramalswasthya/cho/ui/commons/personal_details/PersonalDetailsFragment.kt
> +        withContext(Dispatchers.Main) {
I think there is no need to Dispatchers.Main

2024-11-20 09:56 UTC, closed without merging